### ISSUE TITLE
[Debug] Only support line break point but no support for debugging through multiple statements in one-line

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [adamdriscoll/poshtools#147] opened 2014-12-10 22:03 UTC

**Comment by AndreSayreMSFT** [comment] 2015-01-16 00:39
@HuanhuanSunMSFT we wanted to clarify this one a little bit!  Can you provide more info/example?

**Comment by AndreSayreMSFT** [comment] 2015-04-10 21:56
Dupe of Microsoft#303

**Closed by AndreSayreMSFT** 2015-04-10 21:56 UTC
Labels: bug
