### ISSUE TITLE
Unable to load C# assemblies when debugging - used to work in older version

### ISSUE THREAD

**Issue by BillEidson** [adamdriscoll/poshtools#250] opened 2015-05-01 19:14 UTC
Hi, I have a ps function that loads 5 assemblies, each from specific paths.   The script works in the ISE, standalone, and used to work in Visual Studio using the previous version of this tool set.   The error I am trapping is as follows:

add-type : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
At C:\Program Files\Mirth Connect\scripts\VersionIndependent\core\core.ps1:1502 char:4
+    add-type -Path (
+    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException
    + FullyQualifiedErrorId : System.Reflection.ReflectionTypeLoadException,Microsoft.PowerShell.Commands.AddTypeCommand
 
[ERROR] Import-Module : The extension '.exe' is not a valid module extension. The supported module extensions are '.dll', '.ps1', '.psm1', '.psd1', '.cdxml' and '.xaml'. Correct the extension then try 
[ERROR] adding the file 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\mp0vfvhy.z2c\PowerShellToolsProcessHost.exe' again.
[ERROR] At line:1 char:1
[ERROR] + Import-Module 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\E ...
[ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : PermissionDenied: (:) [Import-Module], InvalidOperationException
[ERROR]     + FullyQualifiedErrorId : Modules_InvalidModuleExtension,Microsoft.PowerShell.Commands.ImportModuleCommand
[ERROR]

**Comment by AndreSayreMSFT** [comment] 2015-05-08 18:42
Dupe of https://github.com/Microsoft/poshtools/issues/511:)

**Closed by AndreSayreMSFT** 2015-05-08 18:42 UTC
