### ISSUE TITLE
[Intellisense] We should be able to format the file without a replacement of types to the complete qualified type.

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [adamdriscoll/poshtools#148] opened 2014-12-10 22:04 UTC

**Comment by AndreSayreMSFT** [comment] 2015-01-16 00:42
Related to #121 and #42

**Comment by AndreSayreMSFT** [comment] 2015-03-10 00:33
Dupe of #42, as we've disabled the functionality as a whole until we get it working.

**Closed by AndreSayreMSFT** 2015-03-10 00:33 UTC
Labels: bug, duplicate
