### ISSUE TITLE
Intellisense, Tab-Completion, and Verb Capitalization

### ISSUE THREAD

**Issue by anweiss** [adamdriscoll/poshtools#79] opened 2014-02-11 18:45 UTC
When using tab-completion with intellisense and upon selecting a cmdlet, the first letter in the verb isn't capitalized.

**Comment by AndreSayreMSFT** [comment] 2015-01-15 23:40
Duplicate of #13, when we fix that one, this should also be fixed!

**Closed by AndreSayreMSFT** 2015-01-15 23:40 UTC
Labels: duplicate
