### ISSUE TITLE
Failed to run script in Debug. VS2013. v3.0.99

### ISSUE THREAD

**Issue by bgoldsht** [adamdriscoll/poshtools#213] opened 2015-04-10 15:50 UTC
Cannot debug in vs2013. PSTools v3.0.99. PS v3.0 OS x64 bit Windows 7
Script:
try
{
    Write-Host "hello";  <--- breakpoint here
}
catch [Exception]
{
    Write-Host $_;
}

Steps:
1. Right mouse click on the script.
2. Select Execute as Script
After that getting next error in debug view

[ERROR] C:\Tools\VSRelated\2013\Visual Studio 2013\Projects\PowerShellProject1\PowerShellProject1\Script.ps1 : Could not load type 'System.Management.Automation.DebuggerCommandResults' from assembly 
[ERROR] 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[ERROR] At line:1 char:1
[ERROR] + . 'C:\Tools\VSRelated\2013\Visual Studio 2013\Projects\PowerShellProject1\PowerS ...
[ERROR] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : NotSpecified: (:) [Script.ps1], TypeLoadException
[ERROR]     + FullyQualifiedErrorId : System.TypeLoadException,Script.ps1
[ERROR]  

Checked .net version. All installed up to 4.5.1

**Comment by EricMSFT** [comment] 2015-04-10 18:30
Thanks for reporting this issue! I think we do have some compatibility issue on PSv3.0, and I m investigating on that now.

**Comment by AndreSayreMSFT** [comment] 2015-04-10 22:40
@bgoldsht Thanks for reporting this! The steps provided were very helpful in identifying root cause. Closing this one as a dupe of #214, we can track things there :)

**Closed by AndreSayreMSFT** 2015-04-10 22:40 UTC
Labels: bug
