### ISSUE TITLE
Pester: Describe -Tag will add the unit test by its tag name instead of by its -Name

### ISSUE THREAD

**Issue by theficus** [adamdriscoll/poshtools#236] opened 2015-04-23 16:42 UTC
3.0.122 build.

There seems to be something strange with the parsing of Describe blocks to pick up the test names.

```powershell
Describe -Tag "P1" -Name "MyTestName" {
}
```
This will add a test to Test Explorer called P1. This seems like incorrect behavior. The tags are for my own marking and filtering, not to be picked up as a name of a test group.

I can work around this by defining my Describe block like this:
```powershell
Describe -Tag ("P1") -Name "MyTestName" {
}
```

**Comment by adamdriscoll** [comment] 2015-04-24 16:03
I think the issue is that I was looking for "Tags" rather than "Tag". I'll make sure this is fixed in the next build.

**Comment by theficus** [comment] 2015-04-24 16:08
Cool. Tags and Tag are the same thing I think anyway. One is just the plural alias to keep in line with PowerShell naming conventions.

--
Sent from my phone. Expect brevity and typos.

On Apr 24, 2015, at 9:03 AM, Adam Driscoll <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the issue is that I was looking for "Tags" rather than "Tag". I'll make sure this is fixed in the next build.

**Closed** 2015-04-25 14:44 UTC
