### ISSUE TITLE
Keyboard shortcuts not working in PowerShell Interactive Window

### ISSUE THREAD

**Issue by BenCamareno** [adamdriscoll/poshtools#472] opened 2016-10-04 23:19 UTC
Hi,

When pressing Ctrl+C, or Ctrl+Z the shortcut won't copy the selected text or Undo last action respectively.
This would then cause for the user to try to copy something and paste the wrong text.

Thanks,

B.C.
##

**Comment by adamdriscoll** [comment] 2017-04-02 16:28
Duplicate of #313

**Closed** 2017-04-02 16:28 UTC
Labels: bug, duplicate
