### ISSUE TITLE
Cannot type upper case "E" after installing latest update

### ISSUE THREAD

**Issue by oatkins** [adamdriscoll/poshtools#303] opened 2015-08-10 14:14 UTC
With version 3.0.170 of these tools installed, Visual Studio interprets an upper case E typed in a C# file as the beginning of a keyboard shortcut. ("(Shift+E) was pressed. Waiting for second key of chord..." appears in status bar.)

I know this is a very odd bug report, so I double checked that a) uninstalling the extension fixes the problem and b) re-installing it does re-introduce the problem.

**Comment by accidentaldeveloper** [comment] 2015-08-10 14:26
I encountered the exact same issue. Uninstalling fixed the problem.

**Comment by adamdriscoll** [comment] 2015-08-10 14:27
Ugh. I'm going to roll back the release on the Gallery for now. Thanks for the report.

**Comment by oatkins** [comment] 2015-08-10 14:43
Thanks.

Shame: "E" is the most common letter in English. I could have gone without "Q" for a bit. But not "E".

**Comment by bryansoto** [comment] 2015-08-10 14:46
I think the problem is the keyboard binding to the EditorContextMenus.CodeWindow.PowerShell.ExecuteAsScript command is set to Shift+E, F5.

In keyboard options, there are actually two entries for it and the previous was Shift+Alt+E, F5. Removing the new one gets my Shift+E back.

**Comment by adamdriscoll** [comment] 2015-08-10 14:55
Ahhhh ok. Nice catch. Thanks!

**Comment by bryansoto** [comment] 2015-08-10 14:59
Not at all. Hope that it helps and thanks for the plugin. :)

**Comment by erwindevreugd** [comment] 2015-08-10 15:59
FYI:
Shift-Control E is mapped to show Resource View, 
Alt-Control E is mapped to Exception dialog, (both by default) so can't use those either.

**Comment by schaneville** [comment] 2015-08-10 17:20
I had the same issue.  Fix from bryansoto solved it for me.

**Comment by adamdriscoll** [comment] 2015-08-10 17:21
What do you guys think would be a good key combo for it?

**Comment by schaneville** [comment] 2015-08-10 17:28
For the record, I have never installed the extension mentioned above (poshtools?  I'm not familiar with it).  While installing or uninstalling that extension may cause the key mapping to be set/unset, I don't think the extension is actually the root cause of the issue.  I installed the updates that came out for VS 2015 today (SSDT update, Azure update, TypeScript update, and a 4th one I can't remember).  I don't know if those installs were related to the issue or not, but I can definitely say that poshtools did not cause it for me.

**Comment by erwindevreugd** [comment] 2015-08-10 17:36
The bug is definitely in poshtools: the change was made in commit e8e27b40.

**Comment by erwindevreugd** [comment] 2015-08-10 17:46
As for the shortcut suggestions: only the Execute as Script command is in the Solution Explorer context menu. I'm not sure what the command is intended to do.

**Comment by adamdriscoll** [comment] 2015-08-11 14:25
This has been fixed in this release: https://github.com/adamdriscoll/poshtools/releases/tag/v3.0.177

**Closed by adamdriscoll** 2015-08-11 14:25 UTC
