### ISSUE TITLE
Strings : Embended Expression Highlighting

### ISSUE THREAD

**Issue by The-New-Guy** [adamdriscoll/poshtools#422] opened 2016-03-02 17:43 UTC
When building a double quoted string you can embed expressions that will evaluate to part of the string.

EX: `$date = "The current date is $(Get-Date -Format 'yyyy-dd-MM')"`

Syntax highlighting is currently showing this entire string as the same color (that of a string). Would be nice if the syntax highlighting detected the `$(<expression>)` and used syntax highlighting you would see if the expression was not inside of a string.
##

**Comment by adamdriscoll** [comment] 2016-03-03 01:08
Thanks for reporting this. It's a duplicate of #342 but I will leave open for now.

**Comment by The-New-Guy** [comment] 2016-03-03 17:21
Thank you, I tried to see if someone had already submitted it but had no results with the terms I used. Sorry for the duplicate.

**Closed** 2017-06-22 20:00 UTC
Labels: bug
